name: Deploy Evaluasaurio App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Obtener el código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 3️⃣ Generar build
      - name: Build project
        run: npm run build  # crea la carpeta dist/

      # 4️⃣ Subir al servidor por SFTP, respetando archivos existentes
      - name: Deploy via SFTP
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          port: ${{ secrets.HOSTINGER_PORT }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          source: "dist/"  # carpeta local generada por npm run build
          target: "/home/u326980243/domains/singularitymx.org/public_html/subproyectos/evaluasaurio/app/"
          recursive: true
          # ✅ No borra archivos existentes fuera de dist
