name: Deploy Evaluasaurio App

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 3. Build del proyecto
      - name: Build project
        run: npm run build  # crea la carpeta dist/

      # 4. Deploy via SFTP
      - name: Deploy Evaluasaurio App via SFTP
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          port: ${{ secrets.HOSTINGER_PORT }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          sync: 
            - local: "dist/"
              remote: "/home/u326980243/domains/singularitymx.org/public_html/subproyectos/evaluasaurio/app/"
          delete: false        # mantiene archivos que no están en local (ej. .htaccess)
